"""Generate Python wrapper files for tools.

Wrappers include rate-limit boilerplate, auth injection, and a
standard invoke() entrypoint. Generated into wrappers/ directory.
"""

from __future__ import annotations

from pathlib import Path

from tooldb.logging import logger
from tooldb.models import Tool

WRAPPERS_DIR = Path("wrappers")

_WRAPPER_TEMPLATE = '''\
"""Auto-generated wrapper for {name}.

Source: {url}
Generated by tooldb wrapper_generator.
"""

from __future__ import annotations

import os
import subprocess
from typing import Any

# ── Auth ──
AUTH_METHOD = {auth_method!r}
AUTH_ENV_VAR = {auth_env_var!r}

# ── Rate limits ──
RATE_LIMIT_PER_HOUR = {rate_limit_per_hour!r}
RATE_LIMIT_PER_SEC = {rate_limit_per_sec!r}

{rate_limiter_block}

def _get_auth() -> str | None:
    """Retrieve auth credential from environment."""
    if AUTH_ENV_VAR:
        val = os.environ.get(AUTH_ENV_VAR)
        if not val:
            raise RuntimeError(f"{{AUTH_ENV_VAR}} env var not set")
        return val
    return None
{oauth_todo}

def invoke(inputs: dict[str, Any]) -> dict[str, Any]:
    """Invoke the tool with given inputs.

    Args:
        inputs: Dict of input parameters.

    Returns:
        Dict with "output", "status", and "duration_ms" keys.
    """
    import time

    start = time.monotonic()

    {invocation_body}

    duration_ms = (time.monotonic() - start) * 1000
    return {{
        "output": result,
        "status": "ok",
        "duration_ms": round(duration_ms, 2),
    }}
'''

_RATE_LIMITER_WITH_LIMITS = """\
# Rate limiter state
_invocation_count_this_hour = 0
_hour_start: float | None = None


def _check_rate_limit() -> None:
    import time

    global _invocation_count_this_hour, _hour_start  # noqa: PLW0603

    now = time.monotonic()
    if _hour_start is None or now - _hour_start > 3600:
        _hour_start = now
        _invocation_count_this_hour = 0

    if RATE_LIMIT_PER_HOUR and _invocation_count_this_hour >= RATE_LIMIT_PER_HOUR:
        raise RuntimeError(f"Rate limit exceeded: {RATE_LIMIT_PER_HOUR}/hour")

    _invocation_count_this_hour += 1
"""

_RATE_LIMITER_NONE = """\
def _check_rate_limit() -> None:
    pass  # No rate limits configured
"""

def _build_invocation_with_template(template: str) -> str:
    """Build invocation body code for a tool with an invocation_template."""
    return (
        "_check_rate_limit()\n"
        "    auth = _get_auth()\n"
        f"    cmd = {template!r}\n"
        "    # Substitute inputs\n"
        "    for key, val in inputs.items():\n"
        '        cmd = cmd.replace(f"{{{key}}}", str(val))\n'
        "    if auth:\n"
        '        cmd = cmd.replace("{auth}", auth)\n'
        "    proc = subprocess.run(\n"
        "        cmd, shell=True, capture_output=True, text=True, timeout=60\n"
        "    )\n"
        "    result = proc.stdout if proc.returncode == 0 else proc.stderr"
    )


_INVOCATION_GENERIC = (
    "_check_rate_limit()\n"
    "    auth = _get_auth()\n"
    "    # Generic invocation — customize this wrapper\n"
    '    result = f"Invoke {inputs} (auth={\'set\' if auth else \'none\'})"'
)


def generate_wrapper(tool: Tool, output_dir: Path | None = None) -> Path:
    """Generate a Python wrapper file for a tool.

    Args:
        tool: Tool to generate wrapper for.
        output_dir: Directory for wrapper file. Defaults to wrappers/.

    Returns:
        Path to the generated wrapper file.
    """
    out_dir = output_dir or WRAPPERS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)

    # Sanitize tool name for filename
    safe_name = tool.name.replace("/", "_").replace(" ", "_").replace("-", "_").lower()
    wrapper_path = out_dir / f"{safe_name}.py"

    rate_block = (
        _RATE_LIMITER_WITH_LIMITS
        if tool.rate_limit_per_hour or tool.rate_limit_per_sec
        else _RATE_LIMITER_NONE
    )

    oauth_todo = ""
    if tool.auth_method == "oauth2":
        oauth_todo = "\n# TODO: Implement OAuth2 flow for this tool\n"

    if tool.invocation_template:
        invocation_body = _build_invocation_with_template(tool.invocation_template)
    else:
        invocation_body = _INVOCATION_GENERIC
        if not tool.rate_limit_per_hour and not tool.rate_limit_per_sec:
            logger.warning(
                "Generating wrapper for %s with no rate limit info", tool.name
            )

    content = _WRAPPER_TEMPLATE.format(
        name=tool.name,
        url=tool.url,
        auth_method=tool.auth_method,
        auth_env_var=tool.auth_env_var,
        rate_limit_per_hour=tool.rate_limit_per_hour,
        rate_limit_per_sec=tool.rate_limit_per_sec,
        rate_limiter_block=rate_block,
        oauth_todo=oauth_todo,
        invocation_body=invocation_body,
    )

    wrapper_path.write_text(content)
    logger.info("Generated wrapper: %s", wrapper_path)
    return wrapper_path
